/**
 * Project id a task (or epic / any project-scoped entity) belongs to. Legacy
 * records without `projectId` are treated as belonging to `fallbackProjectId`
 * (normally the current project) instead of a hard-coded seed project.
 */
export function getTaskProjectId(entity, fallbackProjectId = "") {
  return entity?.projectId || fallbackProjectId || "";
}

/**
 * True when `entity` belongs to `projectId`. Records without `projectId` are
 * attributed to `fallbackProjectId` (defaults to `projectId`, i.e. the current
 * project when filtering the current project's data).
 */
export function isInProject(entity, projectId, fallbackProjectId = projectId) {
  return getTaskProjectId(entity, fallbackProjectId) === (projectId || "");
}

// Task ids are `CY-<digits>` (taskKey / CommentSection rely on that format).
// Older builds used 5 random digits (100k space) which collided easily. New ids
// are time-ordered: seconds since 2024-01-01 followed by 4 random digits, so a
// collision requires two clients to create a task in the same second AND draw
// the same 4 digits. Within one session ids are strictly increasing, and an
// optional collection of existing ids (array, Set, Map keys or task objects)
// is checked as a final guard.
const ID_EPOCH_MS = Date.UTC(2024, 0, 1);
const ID_RANDOM_SPACE = 10000;
let lastIssuedIdNumber = 0;

function randomIdSuffix() {
  const cryptoApi = typeof window !== "undefined" ? window.crypto : undefined;
  if (cryptoApi && typeof cryptoApi.getRandomValues === "function") {
    const buf = new Uint32Array(1);
    cryptoApi.getRandomValues(buf);
    return buf[0] % ID_RANDOM_SPACE;
  }
  return Math.floor(Math.random() * ID_RANDOM_SPACE);
}

function toIdSet(existingIds) {
  if (!existingIds) return null;
  const set = new Set();
  const add = (entry) => {
    if (entry == null) return;
    const id = typeof entry === "object" ? entry.id : entry;
    if (id != null) set.add(String(id));
  };
  if (existingIds instanceof Map) existingIds.forEach((_, key) => add(key));
  else if (typeof existingIds[Symbol.iterator] === "function") {
    for (const entry of existingIds) add(entry);
  }
  return set.size ? set : null;
}

export function generateId(existingIds) {
  const taken = toIdSet(existingIds);
  const seconds = Math.max(0, Math.floor((Date.now() - ID_EPOCH_MS) / 1000));
  let candidate = seconds * ID_RANDOM_SPACE + randomIdSuffix();
  if (candidate <= lastIssuedIdNumber) candidate = lastIssuedIdNumber + 1;
  while (taken && (taken.has(`CY-${candidate}`) || taken.has(String(candidate)))) {
    candidate += 1;
  }
  lastIssuedIdNumber = candidate;
  return `CY-${candidate}`;
}

// Normalises a task id for display — prevents double "CY-CY-" when the stored
// id already carries the prefix (generated by older versions of generateId).
export function taskKey(id) {
  const s = String(id || "");
  return s.startsWith("CY-") ? s : `CY-${s}`;
}
