export function useBoardApi({
  epics,
  labels,
  sprint,
  plannedSprints,
  columns,
  projectColumns,
  activeTasks,
  setActiveTasks,
  backlogSections,
  setBacklogSections,
  allTasks,
  idToGlobalIndex,
  retrospectiveItems,
  notesList,
  pokerHistory,
  burndownSnapshots,
  completedSprints,
  archivedTasks,
  archivedProjects,
  archivedEpics,
  boardSettings,
  boardActions,
}) {
  return {
    epics,
    createEpic: boardActions.createEpic,
    updateEpic: boardActions.updateEpic,
    deleteEpic: boardActions.deleteEpic,
    labels,
    createLabel: boardActions.createLabel,
    deleteLabel: boardActions.deleteLabel,
    sprint,
    startSprint: boardActions.startSprint,
    completeSprint: boardActions.completeSprint,
    updateSprint: boardActions.updateSprint,
    plannedSprints,
    createPlannedSprint: boardActions.createPlannedSprint,
    deletePlannedSprint: boardActions.deletePlannedSprint,
    columns,
    renameColumn: boardActions.renameColumn,
    createColumn: boardActions.createColumn,
    deleteColumn: boardActions.deleteColumn,
    reorderColumns: boardActions.reorderColumns,
    projectColumns,
    updateProjectColumns: boardActions.updateProjectColumns,
    activeTasks,
    setActiveTasks,
    backlogSections,
    setBacklogSections,
    allTasks,
    idToGlobalIndex,
    updateActiveTask: boardActions.updateActiveTask,
    createTask: boardActions.createTask,
    deleteTask: boardActions.deleteTask,
    updateBacklogTask: boardActions.updateBacklogTask,
    createBacklogSection: boardActions.createBacklogSection,
    deleteBacklogSection: boardActions.deleteBacklogSection,
    renameBacklogSection: boardActions.renameBacklogSection,
    handleBacklogDragEnd: boardActions.handleBacklogDragEnd,
    retrospectiveItems,
    addRetroItem: boardActions.addRetroItem,
    updateRetroItem: boardActions.updateRetroItem,
    deleteRetroItem: boardActions.deleteRetroItem,
    voteRetroItem: boardActions.voteRetroItem,
    toggleRetroItem: boardActions.toggleRetroItem,
    setRetroItemEditing: boardActions.setRetroItemEditing,
    notesList,
    addNote: boardActions.addNote,
    deleteNote: boardActions.deleteNote,
    pokerHistory,
    savePokerResult: boardActions.savePokerResult,
    burndownSnapshots,
    completedSprints,
    archivedTasks,
    archivedProjects,
    archivedEpics,
    restoreTask: boardActions.restoreTask,
    permanentDeleteTask: boardActions.permanentDeleteTask,
    emptyArchive: boardActions.emptyArchive,
    boardSettings,
    updateBoardSettings: boardActions.updateBoardSettings,
  };
}
