export function useTestingApi({
  releases,
  testPlans,
  setTestPlans,
  testSuites,
  setTestSuites,
  testCases,
  setTestCases,
  testRuns,
  setTestRuns,
  testingActions,
}) {
  return {
    releases,
    createRelease: testingActions.createRelease,
    updateRelease: testingActions.updateRelease,
    deleteRelease: testingActions.deleteRelease,
    addChangelogEntry: testingActions.addChangelogEntry,
    deleteChangelogEntry: testingActions.deleteChangelogEntry,
    testPlans,
    setTestPlans,
    createTestPlan: testingActions.createTestPlan,
    updateTestPlan: testingActions.updateTestPlan,
    deleteTestPlan: testingActions.deleteTestPlan,
    testSuites,
    setTestSuites,
    createTestSuite: testingActions.createTestSuite,
    updateTestSuite: testingActions.updateTestSuite,
    deleteTestSuite: testingActions.deleteTestSuite,
    testCases,
    setTestCases,
    createTestCase: testingActions.createTestCase,
    updateTestCase: testingActions.updateTestCase,
    deleteTestCase: testingActions.deleteTestCase,
    testRuns,
    setTestRuns,
    createTestRun: testingActions.createTestRun,
    createTestRuns: testingActions.createTestRuns,
    updateTestRun: testingActions.updateTestRun,
    deleteTestRun: testingActions.deleteTestRun,
    updateTestRunResult: testingActions.updateTestRunResult,
  };
}
