export function useTestingApi({
  releases,
  testPlans,
  setTestPlans,
  testSuites,
  setTestSuites,
  testCases,
  setTestCases,
  testRuns,
  setTestRuns,
  testSharedSteps,
  setTestSharedSteps,
  testingActions,
}) {
  return {
    releases,
    createRelease: testingActions.createRelease,
    updateRelease: testingActions.updateRelease,
    deleteRelease: testingActions.deleteRelease,
    addChangelogEntry: testingActions.addChangelogEntry,
    deleteChangelogEntry: testingActions.deleteChangelogEntry,
    updateChangelogEntry: testingActions.updateChangelogEntry,
    importReleases: testingActions.importReleases,
    removeSampleReleases: testingActions.removeSampleReleases,
    moveReleaseTasks: testingActions.moveReleaseTasks,
    testPlans,
    setTestPlans,
    createTestPlan: testingActions.createTestPlan,
    updateTestPlan: testingActions.updateTestPlan,
    deleteTestPlan: testingActions.deleteTestPlan,
    testSuites,
    setTestSuites,
    createTestSuite: testingActions.createTestSuite,
    updateTestSuite: testingActions.updateTestSuite,
    moveTestSuite: testingActions.moveTestSuite,
    deleteTestSuite: testingActions.deleteTestSuite,
    testCases,
    setTestCases,
    createTestCase: testingActions.createTestCase,
    updateTestCase: testingActions.updateTestCase,
    bulkUpdateTestCases: testingActions.bulkUpdateTestCases,
    moveTestCases: testingActions.moveTestCases,
    cloneTestCases: testingActions.cloneTestCases,
    deleteTestCase: testingActions.deleteTestCase,
    deleteTestCases: testingActions.deleteTestCases,
    addTestCaseComment: testingActions.addTestCaseComment,
    deleteTestCaseComment: testingActions.deleteTestCaseComment,
    testSharedSteps,
    setTestSharedSteps,
    createSharedSteps: testingActions.createSharedSteps,
    updateSharedSteps: testingActions.updateSharedSteps,
    deleteSharedSteps: testingActions.deleteSharedSteps,
    testRuns,
    setTestRuns,
    createTestRun: testingActions.createTestRun,
    createTestRuns: testingActions.createTestRuns,
    updateTestRun: testingActions.updateTestRun,
    deleteTestRun: testingActions.deleteTestRun,
    updateTestRunScope: testingActions.updateTestRunScope,
    recordTestExecution: testingActions.recordTestExecution,
    updateTestRunResult: testingActions.updateTestRunResult,
    cloneTestRun: testingActions.cloneTestRun,
    linkDefectToExecution: testingActions.linkDefectToExecution,
    importTestingData: testingActions.importTestingData,
    removeSampleTestingData: testingActions.removeSampleTestingData,
  };
}
