export function useWorkspaceApi({
  currentUser,
  setCurrentUser,
  projects,
  setProjects,
  currentProjectId,
  setCurrentProjectId,
  teams,
  users,
  deletedUserIds,
  teamMembers,
  sprintDefaults,
  workspaceActions,
}) {
  return {
    currentUser,
    setCurrentUser,
    projects,
    setProjects,
    currentProjectId,
    setCurrentProjectId,
    createProject: workspaceActions.createProject,
    updateProject: workspaceActions.updateProject,
    deleteProject: workspaceActions.deleteProject,
    teams,
    createTeam: workspaceActions.createTeam,
    updateTeam: workspaceActions.updateTeam,
    deleteTeam: workspaceActions.deleteTeam,
    users,
    deletedUserIds,
    createUser: workspaceActions.createUser,
    updateUser: workspaceActions.updateUser,
    deleteUser: workspaceActions.deleteUser,
    teamMembers,
    sprintDefaults,
    updateSprintDefaults: workspaceActions.updateSprintDefaults,
  };
}
