import {
  BOARD_FILTER_TYPE_OPTIONS as TASK_BOARD_FILTER_TYPE_OPTIONS,
  TASK_PRIORITY_OPTIONS,
  TASK_STATUS_OPTIONS,
  TASK_SUBTASK_STATUS_OPTIONS,
  TASK_TYPE_OPTIONS,
} from "../../../shared/constants/taskMeta";

export const TYPE_OPTIONS = TASK_TYPE_OPTIONS;
export const BOARD_FILTER_TYPE_OPTIONS = TASK_BOARD_FILTER_TYPE_OPTIONS;
export const STATUS_OPTIONS = TASK_STATUS_OPTIONS;
export const SUBTASK_STATUS_OPTIONS = TASK_SUBTASK_STATUS_OPTIONS;
export const PRIORITY_OPTIONS = TASK_PRIORITY_OPTIONS;

export const ASSIGNEE_LIST = ["unassigned"];
