import { parseIsoDate } from "./dates";

const MONTH_LABELS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

export function formatMoney(amount, currency) {
  const value = Number(amount);
  if (!Number.isFinite(value)) return "—";
  const rounded = Math.round(value * 100) / 100;
  const code = String(currency || "").trim();
  if (/^[A-Z]{3}$/.test(code)) {
    try {
      return new Intl.NumberFormat("en-US", { style: "currency", currency: code, maximumFractionDigits: 2 }).format(rounded);
    } catch {
      // fall through to the plain format
    }
  }
  return `${code}${code && code.length > 1 ? " " : ""}${rounded.toLocaleString("en-US", { maximumFractionDigits: 2 })}`;
}

/**
 * Builds *estimated* monthly pay statements from the employee's contract data.
 * There is no payroll integration — these are derived client-side and must be labelled as estimates.
 *
 * - Annual salary  → salary / 12 per month
 * - Monthly salary → salary per month
 * - Hourly rate    → rate × approved work hours logged in that month
 *
 * Statements start at contractStartDate/startDate (max `limit` months back) and end at the last
 * completed month before `now`.
 */
export function buildPayslipEstimates(employeeProfile, timeEntries = [], now = new Date(), limit = 12) {
  const profile = employeeProfile || {};
  const salary = Number(profile.salary);
  if (!Number.isFinite(salary) || salary <= 0) return [];
  const start = parseIsoDate(profile.contractStartDate) || parseIsoDate(profile.startDate);
  if (!start) return [];

  const salaryType = profile.salaryType || "Annual";
  const currency = profile.salaryCurrency || "";
  const lastCompleted = new Date(now.getFullYear(), now.getMonth() - 1, 1);
  const firstMonth = new Date(start.getFullYear(), start.getMonth(), 1);
  const statements = [];

  const cursor = new Date(lastCompleted);
  while (cursor >= firstMonth && statements.length < limit) {
    const year = cursor.getFullYear();
    const month = cursor.getMonth();
    const prefix = `${year}-${String(month + 1).padStart(2, "0")}`;
    let gross;
    let basis;
    if (salaryType === "Hourly") {
      const hours = (timeEntries || [])
        .filter((entry) => entry.status === "approved" && (entry.type || "work") === "work" && String(entry.date).startsWith(prefix))
        .reduce((sum, entry) => sum + (Number(entry.hours) || 0), 0);
      gross = hours * salary;
      basis = `${Math.round(hours * 10) / 10}h approved × ${formatMoney(salary, currency)}`;
    } else if (salaryType === "Monthly") {
      gross = salary;
      basis = "Monthly salary";
    } else {
      gross = salary / 12;
      basis = "Annual salary ÷ 12";
    }
    statements.push({
      id: `payslip-${prefix}`,
      period: prefix,
      label: `${MONTH_LABELS[month]} ${year}`,
      gross: Math.round(gross * 100) / 100,
      currency,
      basis,
      salaryType,
    });
    cursor.setMonth(cursor.getMonth() - 1);
  }
  return statements;
}

export function payslipToText(statement, { employeeName = "", jobTitle = "", employeeNumber = "" } = {}) {
  return [
    "ESTIMATED PAY STATEMENT",
    "Generated by Corechestra HR from contract data. Not an official payslip — no payroll system is connected.",
    "",
    `Employee:        ${employeeName || "—"}`,
    `Job title:       ${jobTitle || "—"}`,
    `Employee number: ${employeeNumber || "—"}`,
    `Period:          ${statement.label} (${statement.period})`,
    `Basis:           ${statement.basis}`,
    `Estimated gross: ${formatMoney(statement.gross, statement.currency)}`,
    "",
    `Generated at ${new Date().toISOString()}`,
  ].join("\n");
}
