import { useAppStateDomains } from "./useAppStateDomains";
import { useAppStore } from "../../store/useAppStore";
import { useActivityActions } from "./actions/useActivityActions";
import { useBoardActions } from "./actions/useBoardActions";
import { useDocsActions } from "./actions/useDocsActions";
import { useNotificationActions } from "./actions/useNotificationActions";
import { useSystemActions } from "./actions/useSystemActions";
import { useTestingActions } from "./actions/useTestingActions";
import { useWorkspaceActions } from "./actions/useWorkspaceActions";
import { useBoardApi } from "./api/useBoardApi";
import { useDocsApi } from "./api/useDocsApi";
import { useTestingApi } from "./api/useTestingApi";
import { useUiApi } from "./api/useUiApi";
import { useWorkspaceApi } from "./api/useWorkspaceApi";

export function useApp() {
  const dbReady = useAppStore((state) => state.dbReady);
  const state = useAppStateDomains();
  const {
    projects,
    setProjects,
    currentProjectId,
    setCurrentProjectId,
    epics,
    setEpics,
    labels,
    setLabels,
    perProjectSprint,
    setPerProjectSprint,
    projectColumns,
    setProjectColumns,
    activeTasks,
    setActiveTasks,
    perProjectBacklog,
    setPerProjectBacklog,
    setPerProjectRetrospective,
    setPerProjectPokerHistory,
    setPerProjectNotes,
    setPerProjectBoardSettings,
    currentUser,
    setCurrentUser,
    globalActivityLog,
    setGlobalActivityLog,
    notifications,
    setNotifications,
    notificationPreferences,
    setNotificationPreferences,
    setPerProjectBurndownSnapshots,
    teams,
    setTeams,
    users,
    setUsers,
    deletedUserIds,
    setDeletedUserIds,
    sprintDefaults,
    setSprintDefaults,
    spaces,
    setSpaces,
    docPages,
    setDocPages,
    releases,
    setReleases,
    testPlans,
    setTestPlans,
    testSuites,
    setTestSuites,
    testCases,
    setTestCases,
    testRuns,
    setTestRuns,
    setPerProjectCompletedSprints,
    perProjectPlannedSprints,
    setPerProjectPlannedSprints,
    archivedTasks,
    setArchivedTasks,
    archivedProjects,
    setArchivedProjects,
    archivedEpics,
    setArchivedEpics,
    darkMode,
    setDarkMode,
    sidebarCollapsed,
    setSidebarCollapsed,
    projectsViewMode,
    setProjectsViewMode,
    densityMode,
    setDensityMode,
    perProjectBoardFilters,
    setPerProjectBoardFilters,
    templateRegistry,
    setTemplateRegistry,
    savedViews,
    setSavedViews,
    recentItems,
    setRecentItems,
    favoriteItems,
    setFavoriteItems,
    pinnedItems,
    setPinnedItems,
    permissionMatrix,
    setPermissionMatrix,
    workspaceSettings,
    setWorkspaceSettings,
    sensitiveActionPolicy,
    setSensitiveActionPolicy,
    columns,
    sprint,
    setSprint,
    backlogSections,
    setBacklogSections,
    retrospectiveItems,
    setRetrospectiveItems,
    pokerHistory,
    setPokerHistory,
    notesList,
    setNotesList,
    boardSettings,
    setBoardSettings,
    burndownSnapshots,
    completedSprints,
    plannedSprints,
    allTasks,
    idToGlobalIndex,
    teamMembers,
  } = state;

  const { logActivity, logAuditEvent } = useActivityActions({
    currentProjectId,
    currentUser,
    setGlobalActivityLog,
    setActiveTasks,
    setPerProjectBacklog,
  });

  const { addNotification, markNotifRead, markAllNotifsRead } = useNotificationActions({
    setNotifications,
    notificationPreferences,
  });

  const workspaceActions = useWorkspaceActions({
    currentProjectId,
    projects,
    workspaceSettings,
    setProjects,
    setProjectColumns,
    setPerProjectSprint,
    setPerProjectBacklog,
    setPerProjectRetrospective,
    setPerProjectPokerHistory,
    setPerProjectNotes,
    setPerProjectBoardSettings,
    setPerProjectCompletedSprints,
    setPerProjectPlannedSprints,
    setTeams,
    setUsers,
    setDeletedUserIds,
    setSprintDefaults,
    addNotification,
    logAuditEvent,
  });

  const boardActions = useBoardActions({
    currentProjectId,
    currentUser,
    activeTasks,
    perProjectBacklog,
    perProjectSprint,
    perProjectPlannedSprints,
    projects,
    epics,
    archivedTasks,
    archivedProjects,
    archivedEpics,
    sprint,
    backlogSections,
    setActiveTasks,
    setBacklogSections,
    setPerProjectBacklog,
    setArchivedTasks,
    setArchivedProjects,
    setArchivedEpics,
    setSprint,
    setPerProjectCompletedSprints,
    setPerProjectPlannedSprints,
    setProjects,
    setProjectColumns,
    setPerProjectBoardSettings,
    setEpics,
    setLabels,
    setRetrospectiveItems,
    setNotesList,
    setPokerHistory,
    setBoardSettings,
    setPerProjectBacklogMap: setPerProjectBacklog,
    setCompletedSprintMap: setPerProjectCompletedSprints,
    logActivity,
    addNotification,
  });

  const docsActions = useDocsActions({
    currentUser,
    setSpaces,
    setDocPages,
  });

  const testingActions = useTestingActions({
    currentUser,
    templateRegistry,
    setReleases,
    setTestPlans,
    setTestSuites,
    setTestCases,
    setTestRuns,
  });

  const { resetAllData } = useSystemActions({
    setProjects,
    setCurrentProjectId,
    setCurrentUser,
    setEpics,
    setLabels,
    setSprint,
    setProjectColumns,
    setPerProjectSprint,
    setActiveTasks,
    setPerProjectBacklog,
    setPerProjectRetrospective,
    setPerProjectPokerHistory,
    setPerProjectNotes,
    setPerProjectBoardSettings,
    setGlobalActivityLog,
    setNotifications,
    setPerProjectBurndownSnapshots,
    setTeams,
    setUsers,
    setDeletedUserIds,
    setSprintDefaults,
    setSpaces,
    setDocPages,
    setReleases,
    setTestPlans,
    setTestSuites,
    setTestCases,
    setTestRuns,
    setPerProjectCompletedSprints,
    setPerProjectPlannedSprints,
    setArchivedTasks,
    setArchivedProjects,
    setArchivedEpics,
    setDarkMode,
    setSidebarCollapsed,
    setProjectsViewMode,
    setDensityMode,
    setPerProjectBoardFilters,
    setTemplateRegistry,
    setSavedViews,
    setRecentItems,
    setFavoriteItems,
    setPinnedItems,
    setNotificationPreferences,
    setPermissionMatrix,
    setWorkspaceSettings,
    setSensitiveActionPolicy,
  });

  const workspaceApi = useWorkspaceApi({
    currentUser,
    setCurrentUser,
    projects,
    setProjects,
    currentProjectId,
    setCurrentProjectId,
    teams,
    users,
    deletedUserIds,
    teamMembers,
    sprintDefaults,
    workspaceActions,
  });

  const boardApi = useBoardApi({
    epics,
    labels,
    sprint,
    plannedSprints,
    columns,
    projectColumns,
    activeTasks,
    setActiveTasks,
    backlogSections,
    setBacklogSections,
    allTasks,
    idToGlobalIndex,
    retrospectiveItems,
    notesList,
    pokerHistory,
    burndownSnapshots,
    completedSprints,
    archivedTasks,
    archivedProjects,
    archivedEpics,
    boardSettings,
    boardActions,
  });

  const docsApi = useDocsApi({
    spaces,
    docPages,
    docsActions,
  });

  const testingApi = useTestingApi({
    releases,
    testPlans,
    setTestPlans,
    testSuites,
    setTestSuites,
    testCases,
    setTestCases,
    testRuns,
    setTestRuns,
    testingActions,
  });

  const uiApi = useUiApi({
    resetAllData,
    dbReady,
    darkMode,
    setDarkMode,
    sidebarCollapsed,
    setSidebarCollapsed,
    projectsViewMode,
    setProjectsViewMode,
    densityMode,
    setDensityMode,
    perProjectBoardFilters,
    setPerProjectBoardFilters,
    templateRegistry,
    setTemplateRegistry,
    savedViews,
    setSavedViews,
    recentItems,
    setRecentItems,
    favoriteItems,
    setFavoriteItems,
    pinnedItems,
    setPinnedItems,
    notificationPreferences,
    setNotificationPreferences,
    permissionMatrix,
    setPermissionMatrix,
    workspaceSettings,
    setWorkspaceSettings,
    sensitiveActionPolicy,
    setSensitiveActionPolicy,
    globalActivityLog,
    logActivity,
    notifications,
    addNotification,
    markNotifRead,
    markAllNotifsRead,
    currentUser,
  });

  return {
    ...workspaceApi,
    ...boardApi,
    ...uiApi,
    ...docsApi,
    ...testingApi,
    logAuditEvent,
  };
}
